Update portal
TimotheCity/digilan-token pull request #1
Opened 2022-11-10 12:48 UTC by TimotheCity

2022-11-10 21:46 UTC, nathangobinet requested changes

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +    });
Pourquoi cela n'est pas fait en css ?

```css
.flag:hover + button {
  display: block;
}

.lang-flag-delete {
  display: block;
}
```

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      var listItems = $("#language_list li");
var

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +          $(li).css('display', '');
Invalid display. Block ? Inline block ?

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +        type: 'post',
POST en majuscule

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +          'lang': lang,
Pas de ''

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +          location.reload();
C'est barbare, tu peux pas l'ajouter dynamiquement en js ?

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +       }, 100);
Il y'a partout des fonctions sans le raccourcis () => {...}, il faut rester consistant

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      sibling = currentElement.nextElementSibling;
Définition des variables ? let ?

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      };
Je sais pas ce que c'est que ca mais ca me semble très gitant. + Pas de ; après un while

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +    $('.delete-field').on('click', function (value) {
Saut de ligne entre deux fonctions ce serait mieux ? Ca vaut partout

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      let isChecked = value.target.checked
;

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      let resetButton = $(row).find("input[name='reset-changes-button']")[0];
Fait une vérification qu'il y'a bien qq chose avant de pick [0]

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +        isNoChanges = fields[i].value === user_form_fields[field_name][property][lang];
Ca sort d'ou ce truc ? user_form_fields

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      }
for

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      if (isNoChanges) {
Saut de ligne avant

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      $(value.target).attr('disabled', true);
${this} ?

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +        [prefix, property, field_name, lang] = fields[i].name.split('/');
let ? Il faut mettre un mot avant de définir des variables 😳

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +        [prefix, property, field_name, lang] = fields[i].name.split('/');
let ? Il faut mettre un mot avant de définir des variables 😳

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      $('label[name="options"]').children('.required_input').removeAttr("required");
Créer une variable puis appel 
```js
let options = $('label[name="options"]');
options.css('display', 'none');
options.children('.required_input').removeAttr("required");
```

ou chain

```js
$('label[name="options"]')
  .css('display', 'none')
  .children('.required_input')
  .removeAttr("required");
```

Mais la il y'a deux recherche dans le DOM pour la même chose

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +          $('label[name="options"]').children('.required_input').attr("required", true);
Met ca dans une fonction et appelle si radio ou select

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      document.getElementById("new-field-type").value = type;
Attention à l'utilisage des doubles quotes. Essaye d'être consistent. Cela vaut partout.

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      let copyButton = document.getElementById("copy-shortcode");
$(this) ?

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      let copyText = document.getElementById("form-shortcode");
$(this).first() ou $(this).next() ?

De manière générale il vaut mieux essayer de multiplier les appels DOM trop couteux

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      copyText.setSelectionRange(0, 99999);
Comment tu peux le select et mettre une range si c'est un text. Si c'est une input le nom de variable n'est pas bon.

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      $(this).addClass('success');
Parfois this , parfois copyButton 😛

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +    });
Pourquoi il y'a une duplication de code entre les deux fichiers ?

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +    $('#language_list li').click(function(){
Cela ne devrait pas être possible de cliquer sur des li. Il y'a un problème d'accessibilité. Uniquement les liens et les boutons peuvent être cliquer.

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +          location.reload();
Comme précedemment

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +    })
Pourquoi cela est fait en javascript ?

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +      {
Saut de ligne inutile

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +      _name = 'dlt-' + key ;
_name ?
Pourquoi un undescore ?
Pourquoi pas de let ?

2022-11-10 21:46 UTC, nathangobinet commented on js/user-form.js
> +      $('input[name="' + _name + '"]').on("change", function updated_data() {
Pourquoi utliser une fonction non anonyme ?

2022-11-10 21:46 UTC, nathangobinet commented on js/admin/user-form-settings.js
> +      }, "2000");
chaine de caractère à la place d'un number ?

2022-11-15 10:05 UTC, TimotheCity commented on js/admin/user-form-settings.js
> +    });
Pour que je m'entraine en jQuerry :)

2022-11-15 10:50 UTC, TimotheCity commented on js/admin/user-form-settings.js
> +        isNoChanges = fields[i].value === user_form_fields[field_name][property][lang];
Dans `digilan-token.pop` (L550) :

`            $user_form_fields = get_option('user_form_fields');
            wp_localize_script('dlt-user-form-fields', 'user_form_fields', $user_form_fields);`

2022-11-15 14:11 UTC, TimotheCity commented on js/user-form.js
> +    })
Pour éviter de l'écrire partout en phtml, je sais pas si c'était judicieux

2022-11-15 15:29 UTC, TimotheCity commented on js/user-form.js
> +    });
Les scripts sont localisé:
`user-form.js` est utilisé sur la page du formulaire
`user-form-settings.js` sur la page de settings

Pour ne pas dupliquer le code, je peux créer un fichier avec juste cette fonction et `wp_register_script` sur les 2 pages

2022-11-15 17:05 UTC, nathangobinet approved these changes
JS ok ✅

2022-11-17 13:19 UTC, TimotheCity commented on admin/digilan-admin.php
> +        add_action('wp_ajax_digilan-token-form-language-settings', 'DigilanTokenAdmin::update_form_language');
kjdzakjdza

2022-11-17 13:44 UTC, GroupeCitypassengerInc requested changes

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on admin/digilan-admin.php
> +        );
Please use a loop here , it s php , it can do that but usual reader will have trouble this javascript like 
also, it s kinda bad because the function is recompile completly each time

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on admin/digilan-admin.php
> +            self::update_user_form_fields();
put the exist here not inside the sub routine for clarity

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on admin/digilan-admin.php
> +    }
Unsure why you have position inside an ARRAY, it s already positional.

Maybe INSERTING / MOVING the element at the right position instead of managing a index would be way more clean ( and easier to read the code )

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on admin/digilan-admin.php
> +        $form_languages = get_option('form_languages');
If that is the get_option of the wp api the KEY must be prefixed and more precise 

This assume ALL the PORTAL share the same conf ?

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on admin/digilan-admin.php
> +        update_user_meta($user_id,'user_lang',$lang_code);
https://developer.wordpress.org/reference/functions/get_current_user_id/ or ZERO if not logged 

it s never a good practice to ignore returns and documentation ( get_option can fail to )

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on admin/digilan-admin.php
> +    {
any reason to perform sanitize, get_option databases read and the only update_user_meta or only update option, ? one function doing both would be enough no ?

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +
so yeah there s offical rule about plugins in wordpress and naming policy , all the option need to be named more precisely

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +            );
for loop and explicit die on sanitize failed

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +            );
also sanitize should now the type of data , this code is not very clear, is it actually testing the type and value coming from the user ?

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +        return $user_lang_key ?? array_keys($langs)[0];
cute ?? but again not easy to read, moreover this default should not be first in a default but a get_option('dlt_default_lang')  or the default language of the all wordpress

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +
' everywhere but there "  and naming is wrong

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +
search_for_lang_by_code could be a for loop and have the array

this is just making the serveur work for nothing ( go over array to create a new one, then go over the new array to find a key ... ) 

and it does not provide any hint to a reader ( especially a non multi language experienced one )

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on includes/digilan-db.php
> +            );",
i know it s incorrect in other part of code but if possble use the version instead of _1

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on includes/digilan-db.php
> +                `user_info` VARCHAR(1024),
why 1024 ?

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on includes/digilan-db.php
> +                `user_info` VARCHAR(1024),
this limit does not appear anywhere elese

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on includes/digilan-sanitize.php
> +                    return $unsafe_value;
so this is the real lsanitize but when called earlier it s hidden , and why calll a global sanitize_get then if case in it ?

=> create a sanitize dlt-user-form-hidden and make code readable 

it s more custom_form_portal than dlt-user-form- ( all form are used by a user ) ... you re working on the portal_form to make it custom.

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on includes/digilan-user-form.php
> +        }
pretty sure any php coder is screaming in pain here , check ob_start , the fact that stdout is going out and how to do a template in php ?

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on includes/digilan-user-form.php
> +                    alt="'. $lang["name"] .' flag"
please check other code and documentation , it s really hard to read ( you did not evuse a multiline var with << )

2022-11-17 13:44 UTC, GroupeCitypassengerInc commented on providers/mail/mail.php
> +            array(),
same comment use procedural style

2022-11-17 15:09 UTC, TimotheCity commented on admin/digilan-admin.php
> +        );
Just a classic `foreach` loop ?
`foreach ($_POST as $key -> $value);`

2022-11-17 16:04 UTC, TimotheCity commented on includes/digilan-db.php
> +                `user_info` VARCHAR(1024),
I don't know the limite
I can put VARCHAR(MAX) but this has a little impact on performance

2022-11-17 17:24 UTC, GroupeCitypassengerInc commented on includes/digilan-db.php
> +                `user_info` VARCHAR(1024),
https://mariadb.com/kb/en/text/

1/ will you do search on it ?
2/ will you do indexed search on it ?
3/ can you store in a more structured way to have limited filed and unlimited field

Nobody knows the limit; they are changing over time.

check what already exists 
```
describe wp_options;
+--------------+---------------------+------+-----+---------+----------------+
| Field        | Type                | Null | Key | Default | Extra          |
+--------------+---------------------+------+-----+---------+----------------+
| option_id    | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| option_name  | varchar(191)        | NO   | UNI |         |                |
| option_value | longtext            | NO   |     | NULL    |                |
| autoload     | varchar(20)         | NO   | MUL | yes     |                |
+--------------+---------------------+------+-----+---------+----------------+
```

Justify static choice in a comment.

Profit.

2022-11-22 11:52 UTC, TimotheCity commented on admin/digilan-admin.php
> +    {
I have :
- a function to allow admin to add or remove languages of custom portal 
- a function to allow visitor to select dispalyed language of custom portal

2022-11-22 12:29 UTC, dohnuts requested changes

2022-11-22 12:29 UTC, dohnuts commented on admin/digilan-admin.php
> +        );
c est toujours un array_reduce

2022-11-22 13:08 UTC, dohnuts commented on digilan-token.php
> +
Peut on mettre ces machin la dans un fichier à part et le lire ? ( aussi les clef des add_option sont pas prefixé correctement )

2022-11-22 13:10 UTC, dohnuts commented on includes/digilan-user-form.php
> +        }
resolved ou ?

2022-11-22 13:56 UTC, dohnuts requested changes
J'espère que cela fait du sens.

2022-11-22 13:56 UTC, dohnuts commented on admin/digilan-admin.php
> +        }
C est pas une bonne idée de faire cela ici
IE faire un truc automatique pour de la verif
Dans la sous fonction tu as encore le switch case qui a 5 case donc ici 
tu as plus de ligne que de cas

$lang = $lang || 'en' ( utilise une langue default pour simplifier tout au lieu d avoir dedans ou un sous truc qui fait des types mixer qui vont casser le cerveau, 'en' ou meme 'default' )
$new_field_data[$field_option][$lang] = DigilanTokenSanitize::sanitize_post_form_EMAIL_fields($_POST['trucmail']);

2022-11-22 13:56 UTC, dohnuts commented on admin/digilan-admin.php
> +            $input_type = $user_form_fields[$field_name]['type'];
pareil

2022-11-22 13:56 UTC, dohnuts commented on admin/digilan-admin.php
> +        }
en general on commence par la... aussi comment un utilisateur non logger est arrivé jusqu a update_user_language() ???? 

Ce serait bien d avoir un peu de contexte aussi ( c est quoi check_ajax_referer )

2022-11-22 13:56 UTC, dohnuts commented on admin/digilan-admin.php
> +        if (false === $lang) {
Je prefere un sanitize_custom_lang($_value) c est mieux ( pour un tas de raison )

Apres si tu veux garder le concept de faire grep -r '_POST' et verif que tout est dans DigilanTokenSanitize tu faire  DigilanTokenSanitize::sanitize_custom_lang();

( pareil au dessus ) mais evite le on method avec des if c est juste moche ( old code )

2022-11-22 13:56 UTC, dohnuts commented on admin/digilan-admin.php
> +        update_option('digilan_token_form_languages', $form_languages);
dans les languages modernes y a des jolies invert 
la doc city de codage dit que ! est pas lisible ( ici tu fait un invert et c est le sook amr ? ) donc ( cf pr )

2022-11-22 13:56 UTC, dohnuts commented on admin/templates/form-settings.php
> +        alt="<?= $lang['name'] ?> flag"
`<?= plugins_url($src, DLT_ADMIN_PATH) ?>`  comment les autres ???
je sais plus si en php y a aussi <?: pour encoder/raw .. à voir

2022-11-22 13:56 UTC, dohnuts commented on admin/templates/form-settings.php
> +            <?php endif; ?>
`<?= ($is_required) ? "required" ?>`  le plus clair de mémoire

2022-11-22 13:56 UTC, dohnuts commented on admin/templates/form-settings.php
> +  <?php return ob_get_contents();
va la ligne ici ( comme partout ailleurs, cela montre bien que c'est la fin )
<?php
return ob_get_contents();


mais perso je ferais le ob_start / ob_get_content en dehors de la fonction ( et la fonction serait dansun fichie php a part , je suppose vu que c est un template) 

genre ```php
ob_start;
require template_file_new_field_lang_row.php;
ob_get_contents();
```

2022-11-22 13:56 UTC, dohnuts commented on admin/templates/form-settings.php
> +<div class="dlt-admin-content">
si possible aller a la ligne apres le die pour bien voir le debut et pas de \n entre ?> et <div

2022-11-22 13:56 UTC, dohnuts commented on admin/templates/form-settings.php
> +  <h1><?php _e('Form configuration', 'digilan-token'); ?></h1>
un bon moyen de faire mieux que les if required au dessus pareil que _e

2022-11-22 13:56 UTC, dohnuts commented on digilan-token.php
> +        }
pareil en premier verifier le login, apres la db, et c est pas normal qu'un utilisateur non loggé arrive la ! comment est ce possible ?

2022-11-23 13:37 UTC, TimotheCity commented on digilan-token.php
> +        }
Tu m'as dit de check les valeurs de retour, en effet ce n'est pas possible
`https://developer.wordpress.org/reference/functions/get_current_user_id/ or ZERO if not logged`
`it s never a good practice to ignore returns and documentation ( get_option can fail to )`

2022-11-24 10:17 UTC, TimotheCity commented on admin/digilan-admin.php
> +        }
`check_ajax_referer` est utilisé à d'autres endroit dans le plugin
Cela permet de vérifier que la requête ne provient pas d'un autre site

2022-11-24 15:26 UTC, dohnuts requested changes
J ai pas tout review trop de comment

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +                break;
je pense qu il faut appeler wp_die ici pas hooker vers le default

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +            // - dlt-custom-portal-new-field/display-name/fr_FR
pas d iteration sur _POST ! merci

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +        });
array_filter
avec un seul argument ?
`If no callback is supplied, all empty entries of array will be removed. See [empty()](https://www.php.net/manual/en/function.empty.php) for how PHP defines empty in this case.``

donc tu essaie d enlever des null dans des sous tableaux ?

Ces sous tableaux existerais pas si tu avais suivi mes reco précédente: 

langue par default et pas d iteration.

Tout cela est compliqué pour pas grand chose et dur à valider. 

Par ailleurs , les commentaires au dessus aide pas du tout 
`// handle hidden field options without translations (like input type)`

oui on avait compris que y avais pas de langue.... mais cela handle rien

par contre quand tu écris 
``` 
 $new_field_data_filtered = array_filter($new_field_data, function($data) {
            return is_array($data) ? array_filter($data) : $data;
        });
```
pour 
// delete empty value in subarrays

en faisant 4 appel externe sur deux lignes :-/ pour des truc que tu viens de créer c est vraiment tres tres moyen

encore une fois l iteration est pas une bonne idée

Ta liste de post devrait etre plus structuré tu recois genre la liste des champs dans un truc , tu verifies sui leur nom est valide puis tu itere la dessus pour extraire leurs infos.

Aussi des structures dynamiques à type variable c'est trop compliqué , créer la langue DEFAULT ou choisie une langue default et drop le cas pas de langue merci

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +            \DLT\Notices::addError(__('Field name already exist', 'digilan-token'));
Je suppose qu il vaudrait mieux interdires des espaces ,
en tout cas la il faut justifier avec un commentaires pourquoi un espace est enlever ,
en HTML tu peux encoder en (htmlencode ) donc space est %20 des attributs 

Tu peux double check avec @nathangobinet  et la spec html 

Bref à justifier, encoder ou plutôt virer

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +            // $post_key example :
non (*3)

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +    {
Nomme les clairements alors, et check les droits avant de les appeler

2022-11-24 15:26 UTC, dohnuts commented on admin/digilan-admin.php
> +            \DLT\Notices::addError(sprintf(__('Form can\'t be translated in %s.'), $lang));
GOOD

2022-11-24 15:26 UTC, dohnuts commented on admin/templates/form-settings.php
> +            />
fun fact si dns is_required tu met 'class="required_input"' ou rien au lieu de fair eun boolean ( et tu l apelle input_option ) tu peux faire plus et l info est proche de la décision

2022-11-24 15:26 UTC, dohnuts commented on digilan-token.php
> +                        break;
for each inconu do if ( somethingX )  do somethingY
vers
try_do_somethingY(somethingX )

merci ( pas de for pour faire jolie, des fonctions pour faire claire )

2022-11-24 19:13 UTC, dohnuts requested changes

2022-11-24 19:13 UTC, dohnuts commented on admin/digilan-admin.php
> +                }
all of that goes into $user_form_fields[$form_field_key] = routine

self::sanitize_form_field_option_by_type('display-name' cela sert a rien de fair eun switch case dedans apres tu factorise du vide

et lis ton post dedans

aussi un nom de fonction peut etre une variable...

2022-11-29 14:14 UTC, dohnuts commented on admin/templates/form-settings.php
> +            />
je vois pas de résolution la

2022-11-29 14:15 UTC, dohnuts commented on admin/templates/form-settings.php
> +<div class="dlt-admin-content">
et pas de \n entre ?> et <div

2022-11-29 14:17 UTC, dohnuts commented on digilan-token.php
> +        preg_match($css_regex, $override_btn_css, $valid_css_input);
a mon avis quelque commentaires ferais pas de mal dans le coin

2022-11-29 14:18 UTC, dohnuts commented on digilan-token.php
>              }
```php
if ($provider->getState() == 'configured') {
                $provider_id = $provider->getId();
                if ($atts[$provider_id] == 1) {
                    if ($valid_css_input) {
                        $provider->setBtnCss($override_btn_css);
                    }
                    $providersIn[$provider_id] = self::$providers[$provider_id];
                }
            }
```

ce serait pas mal de recoder cela a la mode city 
if ($provider->getState() != 'configured') continue;
$provider_id = $provider->getId();
if ($atts[$provider_id] != 1) continue;

2022-11-29 14:27 UTC, dohnuts requested changes

2022-11-29 14:27 UTC, dohnuts commented on digilan-token.php
> +                $user_info[$form_field_key] = $safe_value;
J voulais accepter mais y a trop de pas ok ici

2022-11-29 14:27 UTC, dohnuts commented on digilan-token.php
> +                $user_info[$form_field_key] = $safe_value;
self::sanitize_custom_portal_input , fait le test isset(arg2) et vire le continue du isset au dessus

Quand un sanitize failed, on continue pas => fait un die dans le sanitize et si le return false est pas un fail
pour le coup tu as pas de early return 

if ($safe_value)  $user_info[$form_field_key] = $safe_value;



et tout le foreach pourrait etre dans 

self::sanitize_custom_portal_inputs($user_info);

2022-11-29 14:27 UTC, dohnuts commented on digilan-token.php
> +                $safe_value = $unsafe_value;
bas si

2022-11-29 14:27 UTC, dohnuts commented on digilan-token.php
> +                $safe_value = $unsafe_value;
https://media.tenor.com/dAjBzKj9H3AAAAAC/danger-alert.gif

2022-11-29 14:27 UTC, dohnuts commented on includes/digilan-user-form.php
> +            }
on peut essayer de faire du php SVP ( avec ob ou en direct comme l autre fichier ?)

2022-11-29 17:55 UTC, dohnuts requested changes
presque ok

2022-11-29 17:55 UTC, dohnuts commented on admin/templates/form-settings.php
> +            title="<?php _e('Number unit', 'digilan-token'); ?>"
pas de pattern

2022-11-29 17:55 UTC, dohnuts commented on admin/templates/form-settings.php
> +            <?php // Use class for jquery to handle "required" with "display:none" conflict when options is hidden ?>
pas de pattern

2022-11-29 17:55 UTC, dohnuts commented on admin/templates/form-settings.php
> +            <?= ($is_required) ? "required" : '' ?>
pas de pattern

2022-11-29 17:55 UTC, dohnuts commented on admin/templates/form-settings.php
> +            style="width:100%"
pas de pattern

2022-11-29 17:55 UTC, dohnuts commented on admin/digilan-admin.php
> +        update_option('digilan_token_form_languages', $form_languages);
dans quel cas un langugage devient non disponible ?

2022-11-30 11:53 UTC, TimotheCity commented on admin/digilan-admin.php
> +        update_option('digilan_token_form_languages', $form_languages);
J'ai fait en sorte que l'admin ait une liste de langues
Il choisit celles qui seront présente dans le portail
Il doit alors fournir les traductions pour ces champs

Donc une liste n'est pas disponible dans le portail si l'admin ne veut pas l'ajouter à son portail

2022-11-30 12:52 UTC, dohnuts commented
Ceci ne reponds pas a la question

regarde le code dans quel cas tu passe dans
$form_languages[$lang]['implemented'] ^= 1; avec
$form_languages[$lang]['implemented'] == 1

?

met donc un log

if ( $form_languages[$lang]['implemented'] == 1 ) {
 error_log ( "deactivating language $lang");
}

et regarde si tu arrive a le faire

On Wed, Nov 30, 2022 at 6:54 AM TimotheCity ***@***.***> wrote:
>
> @TimotheCity commented on this pull request.
>
> ________________________________
>
> In admin/digilan-admin.php:
>
> > +        // flip implemented value
>
> +        $form_languages[$lang]['implemented'] ^= 1;
>
> +        update_option('digilan_token_form_languages', $form_languages);
>
> J'ai fait en sorte que l'admin ait une liste de langues
> Il choisit celles qui seront présente dans le portail
> Il doit alors fournir les traductions pour ces champs
>
> Donc une liste n'est pas disponible dans le portail si l'admin ne veut pas l'ajouter à son portail
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
--
---------------------------------------------------------------------------------------------------------------------
Knowing is not enough; we must apply. Willing is not enough; we must do

2022-11-30 14:49 UTC, GroupeCitypassengerInc approved these changes

2022-11-30 14:51 UTC, merged