Fix sql syntax error, add button to test datatable
TimotheCity/digilan-token pull request #16
Opened 2022-12-06 17:37 UTC by TimotheCity

2022-12-06 17:41 UTC, dohnuts requested changes

2022-12-06 17:41 UTC, dohnuts commented on includes/digilan-db.php
>          return sprintf($sql_users, $wpdb->prefix, self::$installed_version);
non

2022-12-06 17:41 UTC, dohnuts commented on includes/digilan-db.php
> +        ) ENGINE = InnoDB;";
encore plus non

2022-12-06 17:41 UTC, dohnuts commented on includes/digilan-db.php
> +            `user_id` INT,
t'as pas suivie les instructions

2022-12-06 17:46 UTC, TimotheCity commented on includes/digilan-db.php
> +            `user_id` INT,
Non car je voulais avoir quelque chose à tester demain et je ne peux pas changer toutes la structure au moment où je dois partir, parce que ça implique des changements dans tous les fichiers

2022-12-06 17:50 UTC, dohnuts commented on admin/templates/form-settings.php
> +  </form>
t a pas besoin de faire le bouton mais bon pas grave

2022-12-06 17:52 UTC, dohnuts requested changes

2022-12-06 17:52 UTC, dohnuts commented on includes/digilan-db.php
> +                );";
y a pas de ; dans le code ici, tu vois bien cela ailleurs...

2022-12-06 17:52 UTC, dohnuts commented on includes/digilan-db.php
> +        return sprintf($sql_logs, $wpdb->prefix, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version);
pas demandé

2022-12-06 17:52 UTC, dohnuts commented on includes/digilan-db.php
> +        return sprintf($sql_archive_logs, $wpdb->prefix, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version);
pas demandé

2022-12-06 17:52 UTC, dohnuts commented on includes/digilan-db.php
> +        return sprintf($sql_social_users, $wpdb->prefix, self::$installed_version);
pas demandé

2022-12-06 17:52 UTC, dohnuts commented on includes/digilan-db.php
> +        return sprintf($sql_meta_users, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version);
Je ne vois aucun insert modifié, comment ce code pourrait marcher ?

2022-12-06 18:02 UTC, TimotheCity commented on includes/digilan-db.php
> +                );";
Si je regarde ailleurs, c'est 50% pour le ";" et 50% contre

2022-12-06 18:04 UTC, TimotheCity commented on includes/digilan-db.php
> +        return sprintf($sql_meta_users, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version);
SQL est plus cool le soir et ne fais plus d'erreur

2022-12-06 18:20 UTC, dohnuts commented on includes/digilan-db.php
> +        return sprintf($sql_meta_users, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version);
le type JSON permet juste de vérifier la structure, ce serait vraiment bien d avoir quelques colonne sur les champs personnalisé, surtout ceux qui seront recherché

2022-12-07 08:42 UTC, TimotheCity commented on includes/digilan-db.php
> +        return sprintf($sql_meta_users, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version, $wpdb->prefix, self::$installed_version);
Comment ça `surtout ceux qui seront recherchés` ?
Il m'a été demandé d'ajouter au portail de connexion un formulaire demandant des informations à l'utilisateur.
On m'a aussi demandé la possibilité de rajouter/supprimer des champs du formulaire.
J'ai donc créer 4 champs par défauts mais ils peuvent être amener à disparaître

On a donc une table de données qui va recueillir ces informations, mais ces champs pouvant être totalement customisable, il n'y a rien de fixe, donc comment pourrait-il y avoir quelques colonnes de base dans la table ?

2022-12-09 13:41 UTC, dohnuts requested changes
Almost

2022-12-09 13:41 UTC, dohnuts commented on admin/digilan-admin.php
> +            exit();
fait donc un wp_send_json

2022-12-09 13:41 UTC, dohnuts commented on admin/templates/form-settings.php
> +  <div style="margin: 30px 0; display: flex; gap: 20px;">
essaye de commit cela en direct no PR de maniere independante quand tu peux

2022-12-09 13:41 UTC, dohnuts commented on includes/digilan-db.php
>                  FOREIGN KEY `fk_%sdigilan_token_meta_%d` (user_id) REFERENCES %sdigilan_token_users_%d(id)
pour nationality j encourage de prendre le CODE iso deux character officiel et ainsi permettre de faciliter la saisie dans le formulaire 
```html
<select id="country" name="country">
    <option>select country</option>
    <option value="AF">Afghanistan</option>
    <option value="AX">Aland Islands</option>
    <option value="AL">Albania</option>
    <option value="DZ">Algeria</option>
    <option value="AS">American Samoa</option>
    <option value="AD">Andorra</option>
    <option value="AO">Angola</option>
    <option value="AI">Anguilla</option>
    <option value="AQ">Antarctica</option>
    <option value="AG">Antigua and Barbuda</option>
    <option value="AR">Argentina</option>
    <option value="AM">Armenia</option>
    <option value="AW">Aruba</option>
    <option value="AU">Australia</option>
    <option value="AT">Austria</option>
    <option value="AZ">Azerbaijan</option>
    <option value="BS">Bahamas</option>
    <option value="BH">Bahrain</option>
    <option value="BD">Bangladesh</option>
    <option value="BB">Barbados</option>
    <option value="BY">Belarus</option>
    <option value="BE">Belgium</option>
    <option value="BZ">Belize</option>
    <option value="BJ">Benin</option>
    <option value="BM">Bermuda</option>
    <option value="BT">Bhutan</option>
    <option value="BO">Bolivia</option>
    <option value="BQ">Bonaire, Sint Eustatius and Saba</option>
    <option value="BA">Bosnia and Herzegovina</option>
    <option value="BW">Botswana</option>
    <option value="BV">Bouvet Island</option>
    <option value="BR">Brazil</option>
    <option value="IO">British Indian Ocean Territory</option>
    <option value="BN">Brunei Darussalam</option>
    <option value="BG">Bulgaria</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="KH">Cambodia</option>
    <option value="CM">Cameroon</option>
    <option value="CA">Canada</option>
    <option value="CV">Cape Verde</option>
    <option value="KY">Cayman Islands</option>
    <option value="CF">Central African Republic</option>
    <option value="TD">Chad</option>
    <option value="CL">Chile</option>
    <option value="CN">China</option>
    <option value="CX">Christmas Island</option>
    <option value="CC">Cocos (Keeling) Islands</option>
    <option value="CO">Colombia</option>
    <option value="KM">Comoros</option>
    <option value="CG">Congo</option>
    <option value="CD">Congo, Democratic Republic of the Congo</option>
    <option value="CK">Cook Islands</option>
    <option value="CR">Costa Rica</option>
    <option value="CI">Cote D'Ivoire</option>
    <option value="HR">Croatia</option>
    <option value="CU">Cuba</option>
    <option value="CW">Curacao</option>
    <option value="CY">Cyprus</option>
    <option value="CZ">Czech Republic</option>
    <option value="DK">Denmark</option>
    <option value="DJ">Djibouti</option>
    <option value="DM">Dominica</option>
    <option value="DO">Dominican Republic</option>
    <option value="EC">Ecuador</option>
    <option value="EG">Egypt</option>
    <option value="SV">El Salvador</option>
    <option value="GQ">Equatorial Guinea</option>
    <option value="ER">Eritrea</option>
    <option value="EE">Estonia</option>
    <option value="ET">Ethiopia</option>
    <option value="FK">Falkland Islands (Malvinas)</option>
    <option value="FO">Faroe Islands</option>
    <option value="FJ">Fiji</option>
    <option value="FI">Finland</option>
    <option value="FR">France</option>
    <option value="GF">French Guiana</option>
    <option value="PF">French Polynesia</option>
    <option value="TF">French Southern Territories</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GE">Georgia</option>
    <option value="DE">Germany</option>
    <option value="GH">Ghana</option>
    <option value="GI">Gibraltar</option>
    <option value="GR">Greece</option>
    <option value="GL">Greenland</option>
    <option value="GD">Grenada</option>
    <option value="GP">Guadeloupe</option>
    <option value="GU">Guam</option>
    <option value="GT">Guatemala</option>
    <option value="GG">Guernsey</option>
    <option value="GN">Guinea</option>
    <option value="GW">Guinea-Bissau</option>
    <option value="GY">Guyana</option>
    <option value="HT">Haiti</option>
    <option value="HM">Heard Island and Mcdonald Islands</option>
    <option value="VA">Holy See (Vatican City State)</option>
    <option value="HN">Honduras</option>
    <option value="HK">Hong Kong</option>
    <option value="HU">Hungary</option>
    <option value="IS">Iceland</option>
    <option value="IN">India</option>
    <option value="ID">Indonesia</option>
    <option value="IR">Iran, Islamic Republic of</option>
    <option value="IQ">Iraq</option>
    <option value="IE">Ireland</option>
    <option value="IM">Isle of Man</option>
    <option value="IL">Israel</option>
    <option value="IT">Italy</option>
    <option value="JM">Jamaica</option>
    <option value="JP">Japan</option>
    <option value="JE">Jersey</option>
    <option value="JO">Jordan</option>
    <option value="KZ">Kazakhstan</option>
    <option value="KE">Kenya</option>
    <option value="KI">Kiribati</option>
    <option value="KP">Korea, Democratic People's Republic of</option>
    <option value="KR">Korea, Republic of</option>
    <option value="XK">Kosovo</option>
    <option value="KW">Kuwait</option>
    <option value="KG">Kyrgyzstan</option>
    <option value="LA">Lao People's Democratic Republic</option>
    <option value="LV">Latvia</option>
    <option value="LB">Lebanon</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libyan Arab Jamahiriya</option>
    <option value="LI">Liechtenstein</option>
    <option value="LT">Lithuania</option>
    <option value="LU">Luxembourg</option>
    <option value="MO">Macao</option>
    <option value="MK">Macedonia, the Former Yugoslav Republic of</option>
    <option value="MG">Madagascar</option>
    <option value="MW">Malawi</option>
    <option value="MY">Malaysia</option>
    <option value="MV">Maldives</option>
    <option value="ML">Mali</option>
    <option value="MT">Malta</option>
    <option value="MH">Marshall Islands</option>
    <option value="MQ">Martinique</option>
    <option value="MR">Mauritania</option>
    <option value="MU">Mauritius</option>
    <option value="YT">Mayotte</option>
    <option value="MX">Mexico</option>
    <option value="FM">Micronesia, Federated States of</option>
    <option value="MD">Moldova, Republic of</option>
    <option value="MC">Monaco</option>
    <option value="MN">Mongolia</option>
    <option value="ME">Montenegro</option>
    <option value="MS">Montserrat</option>
    <option value="MA">Morocco</option>
    <option value="MZ">Mozambique</option>
    <option value="MM">Myanmar</option>
    <option value="NA">Namibia</option>
    <option value="NR">Nauru</option>
    <option value="NP">Nepal</option>
    <option value="NL">Netherlands</option>
    <option value="AN">Netherlands Antilles</option>
    <option value="NC">New Caledonia</option>
    <option value="NZ">New Zealand</option>
    <option value="NI">Nicaragua</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="NU">Niue</option>
    <option value="NF">Norfolk Island</option>
    <option value="MP">Northern Mariana Islands</option>
    <option value="NO">Norway</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PW">Palau</option>
    <option value="PS">Palestinian Territory, Occupied</option>
    <option value="PA">Panama</option>
    <option value="PG">Papua New Guinea</option>
    <option value="PY">Paraguay</option>
    <option value="PE">Peru</option>
    <option value="PH">Philippines</option>
    <option value="PN">Pitcairn</option>
    <option value="PL">Poland</op [...]

2022-12-09 13:41 UTC, dohnuts commented on includes/digilan-user.php
> +            "%s",
Tu pouvais dupliquer les infos dans le json, c est pas grave par contre

```
stay_length=> $json_customized_user_info->stay_length,
```

Au lieu de trimbalter un user_meta_data et un user_other_meta_data

2022-12-12 14:40 UTC, dohnuts requested changes

2022-12-12 14:40 UTC, dohnuts commented on admin/templates/form-settings.php
> +              </div>
Euuu, tu demandes à l utilsateur de choisir des bornes ? type=number ? cela gère les 'mantises'  genre 10e-3

2022-12-12 14:40 UTC, dohnuts commented on digilan-token.php
> +            'stay-length' => 0,
__ n est pas une valuer par default qui fait du sens

2022-12-12 14:42 UTC, TimotheCity commented on digilan-token.php
> +            'stay-length' => 0,
empty '' fait plus de sens ?

2022-12-12 14:43 UTC, TimotheCity commented on admin/templates/form-settings.php
> +              </div>
C'est une erreur de branche

2022-12-12 15:13 UTC, dohnuts requested changes
Tu essaie de passer des diffs en douce ? je parle de number , tu pousses des textarea ...

2022-12-12 15:16 UTC, TimotheCity commented
@dohnuts tu as parlé de number sur l'autre PR

2022-12-13 15:14 UTC, dohnuts requested changes
Merci d implementer la PR pour une release 
IE:
`Fix sql syntax error, add button to test datatable`

Pas `random feature` pour gagner du temps

2022-12-13 15:14 UTC, dohnuts commented on includes/digilan-custom-portal-constants.php
> +                'fr_FR' => '',
stop using empty string as default value !

2022-12-13 15:14 UTC, dohnuts commented on admin/templates/form-settings.php
> +                  <?php endif; ?>
Séparer cette feature non demand;e dans un autre pr et la garder pour quan dce seras demandé.

2022-12-13 16:59 UTC, dohnuts requested changes
Juste adapter les title , partout

2022-12-13 17:17 UTC, dohnuts commented on providers/mail/mail.php
POST est global

et si tu passait la clef ( cela te donneriasle nom du champ pour les logs ) tu pourrais lire POST toujorus dans sanitize ...

2022-12-13 17:27 UTC, dohnuts requested changes

2022-12-13 17:27 UTC, dohnuts commented on digilan-token.php
> +                }
https://www.php.net/manual/en/function.array-intersect.php
et probablement l union == la taille de  $all_language_options et intersect vide.

pas strstr dans des join STP ?

2022-12-13 17:53 UTC, dohnuts requested changes

2022-12-13 17:53 UTC, dohnuts commented on digilan-token.php
> +                $safe_value = DigilanTokenSanitize::sanitize_custom_form_portal_hidden_options($unsafe_value, $options);
aucun rapport avec le fix demandé

2022-12-13 18:40 UTC, dohnuts requested changes

2022-12-13 18:40 UTC, dohnuts commented on digilan-token.php
> +                $safe_value = DigilanTokenSanitize::sanitize_custom_form_portal_hidden_options($unsafe_value, $options);
Merci de réaprer ce code comme demandé et ne pas faire des strstr dans des concat pour vérifier si l input est valide

2022-12-14 14:20 UTC, dohnuts approved these changes
![nice](https://thumbs.gfycat.com/PeacefulNecessaryGrasshopper-max-1mb.gif)

2022-12-15 10:24 UTC, merged