Fix lang select for non logged user (portal connexion)
TimotheCity/digilan-token pull request #17
Opened 2022-12-07 15:30 UTC by TimotheCity

2022-12-07 15:51 UTC, GroupeCitypassengerInc requested changes

2022-12-07 15:51 UTC, GroupeCitypassengerInc commented on digilan-token.php
> +
non sanitize, crazy code that recreate and reparse the url to access $_GET

2022-12-07 16:11 UTC, TimotheCity commented on digilan-token.php
> +
En effet, c'est mieux avec GET

2022-12-09 13:30 UTC, dohnuts commented on digilan-token.php
> +
faire de la recherche sur `$_SERVER['HTTP_ACCEPT_LANGUAGE']` pour le cas ou y a pas de lang demandé

2022-12-09 13:30 UTC, dohnuts requested changes
cd $_SERVER['HTTP_ACCEPT_LANGUAGE']

2022-12-12 14:42 UTC, dohnuts approved these changes

2022-12-12 14:58 UTC, merged