Fix pattern portal inputs
TimotheCity/digilan-token pull request #18
Opened 2022-12-12 14:30 UTC by TimotheCity

2022-12-12 14:45 UTC, dohnuts requested changes
Je pense qu il y a unmix up de commit avec la 16

c est ok, BUT, y a p asun input pour un range qui existe de base, comme celui que Nathan a en haut des logs ?

2022-12-12 14:45 UTC, dohnuts commented on admin/templates/form-settings.php
> +                    pattern="-?[0-9]\d*(\.\d+)"
ce diff est dans l autre PR , la 16 et au dessus y a number ici text...

2022-12-12 15:01 UTC, TimotheCity commented
Si si, il y a une input range mais cela peut ne pas être pratique à utiliser si la range est trop grande

2022-12-12 15:14 UTC, dohnuts requested changes

2022-12-12 15:14 UTC, dohnuts commented on includes/digilan-custom-portal-constants.php
> +            'max' => '',
chaine vide est pas un chiffre par default... null , absent ,, etc

2022-12-13 16:59 UTC, dohnuts requested changes
sanitize_form_field_number utilise pas

https://www.php.net/manual/en/function.is-numeric.php

check_safe_value_has_error devrait etre direct dans le sanitize,
et renommer die_on_failed_sanitize

sanitize_form_field_unit est pas du tout justifier

le pattern des type number accepte pas 10e1 et Je pense que c est pas utile d avoir un pattern sur un type number , l OS devrait faire , s il fait pas faut rester avec un truc plus gentil car 1,000.0 et 1 000, 0 c est pareil mais pas pareil. 

Pour cela qu il y a un type = number. 

pour 

            $field_ref['min'] = ($safe_min === '') ? null : $safe_min;
            $field_ref['max'] = ($safe_max === '') ? null : $safe_max;
            
            
cela peut etre pas mal d eviter un overflow avec MAX_INT et -MAX_INT...

2022-12-14 13:10 UTC, TimotheCity commented
@dohnuts J'ai pu faire les modifications
Je ne suis juste pas sur si pour `sanitize_form_field_unit ` tu veux dire sa sert à rien ou c'est pas assez précis en terme de nommage

2022-12-14 14:15 UTC, dohnuts requested changes

2022-12-14 14:15 UTC, dohnuts commented on admin/templates/form-settings.php
> +            pattern="[-0-9a-zA-ZÀ-ú\s']*(,[-0-9a-zA-ZÀ-ú\s']*)*"
si c est des mots, utilisé l autre truc , pas cela qui est anti non roman character

2022-12-14 14:15 UTC, dohnuts commented on admin/templates/form-settings.php
> +                    pattern="-?[0-9]\d*(\.\d+)"
y a toujours pas les mantises

2022-12-14 14:15 UTC, dohnuts commented on includes/digilan-sanitize.php
> +        return false;
pourquoi chaine vide c est ok ? et renvoie default ?

2022-12-14 14:15 UTC, dohnuts commented on includes/digilan-sanitize.php
> +        return false;
( semantiquement le sanitize doit pas interpreter , aprs c est pas grave c est juste louche )

2022-12-14 14:15 UTC, dohnuts commented on includes/digilan-sanitize.php
> +            $safe_option = self::sanitize_test_regex_form_settings_input(trim($option), $re, 'options');
non on trim pas coté serveur, on re pour prevenir le user si on gere pas mais on modifie pas ses données dans son dos

2022-12-14 14:15 UTC, dohnuts commented on includes/digilan-sanitize.php
> +            $safe_option = self::sanitize_test_regex_form_settings_input(trim($option), $re, 'options');
et regles city , deux appelles sur meme ligne

2022-12-14 14:28 UTC, TimotheCity commented on includes/digilan-sanitize.php
> +        return false;
@dohnuts Si l'admin ne rentre pas de texte, alors il voit le placeholder `+∞`
Donc empty vaut PHP_INT_MAX

Ce n'est pas correct du coup ?

2022-12-15 13:29 UTC, dohnuts requested changes
∞ Mieux

2022-12-15 13:29 UTC, dohnuts commented on admin/templates/form-settings.php
> +            title="<?php _e('Max', 'digilan-token'); ?>"
Placeholder == example 
Title = Failure explication

2022-12-15 13:29 UTC, dohnuts commented on admin/templates/form-settings.php
> +            title="<?php _e('Max', 'digilan-token'); ?>"
a fix partout

2022-12-15 13:29 UTC, dohnuts commented on admin/templates/form-settings.php
> +                    placeholder="-∞"
non

2022-12-15 13:29 UTC, dohnuts commented on admin/templates/form-settings.php
> +                    placeholder="+∞"
plus

2022-12-15 13:29 UTC, dohnuts commented on includes/digilan-sanitize.php
> +        if ($unsafe_value === '') {
but IS replaced

2022-12-15 13:29 UTC, dohnuts commented on includes/digilan-sanitize.php
> +            return PHP_INT_MAX;
`// Use safe value when empty is chosen`

2022-12-15 14:11 UTC, dohnuts commented on includes/digilan-user-form.php
> +                <option value="" disabled selected>
bug

2022-12-15 14:12 UTC, dohnuts approved these changes

2022-12-15 14:17 UTC, TimotheCity commented on includes/digilan-user-form.php
> +                <option value="" disabled selected>
`disabled selected` ? -> non c'est pour que select affiche l'instruction (ex: `D'où venez vous ?`) mais que l'utilisateur ne puisse pas la sélectionner ensuite

2022-12-15 14:18 UTC, merged