Create table
TimotheCity/digilan-token pull request #25
Opened 2022-12-20 17:07 UTC by TimotheCity

2022-12-20 17:14 UTC, dohnuts requested changes

2022-12-20 17:14 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
rajouter LIMIT et OFFSET pour prendre des pages de ~5000 ou directemetn recup les pages demandé par datatable

2022-12-20 17:14 UTC, dohnuts commented on js/admin/connections.js
> +			"order": [[2, "desc"]],
manque keep state

2022-12-20 17:14 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
verifier si lautre tableau le fait pas correct et copier

2022-12-21 10:30 UTC, TimotheCity commented on includes/digilan-connection.php
> +    }
Je fais comment pour l'autre, sachant qu'il y a deux appels qui sont ensuite merge ?
```
$query_archive = "SELECT ... FROM connexion LEFT JOIN users on connexion.id = user.id
        WHERE {$wpdb->prefix}digilan_token_connections_$version.ap_validation IS NOT NULL;";
```

2022-12-21 10:34 UTC, TimotheCity commented on includes/digilan-connection.php
> +    }
Et quelle valeur mettre pour offset ? nombre de ligne dans la table - 5000 ?

2022-12-21 15:23 UTC, dohnuts requested changes

2022-12-21 15:23 UTC, dohnuts commented on includes/digilan-sanitize.php
>          return self::sanitize_test_regex($unsafe_value, $re);
is_numeric please

2022-12-21 16:38 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
on s en fou pour l instant

2022-12-21 16:38 UTC, dohnuts approved these changes

2022-12-21 16:46 UTC, merged