INNER JOIN over LEFT JOIN to only select if present in both table
TimotheCity/digilan-token pull request #31
Opened 2023-01-05 15:54 UTC by TimotheCity

check match with connection & active session tables

2023-01-05 17:09 UTC, dohnuts requested changes
Je pense que tu te trompe: en effet tu dois chercher dans les deux tables pour que cela  marche en effet les insertions sont fait dans  une pre table puis inserer dans la complète

2023-01-12 13:53 UTC, dohnuts requested changes

2023-01-12 13:53 UTC, dohnuts commented on includes/digilan-connection.php
> +
va juste falloir rajouter un log avant et apres avec un calcul de temps parceque j ai l impression que cest pas top

2023-01-12 15:14 UTC, TimotheCity commented on includes/digilan-connection.php
> +
En faisant la différence entre `hrtime(true)` avant et après sur un échantillons de 250 lignes dans la table connexion
```
start : 173546020045500
end : 173546020047700
diff (en seconde): 2.2E-6 [($end - $start) / 1e+9] 
```

2023-01-13 15:43 UTC, GroupeCitypassengerInc approved these changes

2023-01-13 15:59 UTC, merged