Add download user meta logs button
TimotheCity/digilan-token pull request #33
Opened 2023-01-11 16:35 UTC by TimotheCity

2023-01-11 17:43 UTC, dohnuts requested changes
juste une question

2023-01-11 17:43 UTC, dohnuts commented on admin/digilan-admin.php
> +    if ($sd > $ed) {
100% sur que le new va renvoyer un truc valide ?

2023-01-12 09:21 UTC, TimotheCity commented on admin/digilan-admin.php
> +    if ($sd > $ed) {
`$start` et `$end` sont sanitize juste aussi de la façon suivante :
`case 'dlt-start-date':
  $a = explode('-', $unsafe_value);
  $month = $a[1];
  $year = $a[0];
  $day = $a[2];
  $res = wp_checkdate($month, $day, $year, $unsafe_value);
  if ($res) {
    return $unsafe_value;
  } else {
    return false;
  }
case 'dlt-end-date':
  $a = explode('-', $unsafe_value);
  $month = $a[1];
  $year = $a[0];
  $day = $a[2];
  $res = wp_checkdate($month, $day, $year, $unsafe_value);
  if ($res) {
    return $unsafe_value;
  } else {
    return false;
  }`

2023-01-12 14:00 UTC, dohnuts requested changes

2023-01-12 14:00 UTC, dohnuts commented on admin/digilan-admin.php
> +    if ($sd > $ed) {
```
    $sd = DigilanTokenSanitize::sanitize_post('dlt-start-date');
    if ($sd) {
      $start_date  = new DateTime($start);
    } else {
      \DLT\Notices::addError(__('Invalid start date.', 'digilan-token'));
      wp_redirect(self::getAdminUrl('connections'));
      exit();
    }
    $ed = DigilanTokenSanitize::sanitize_post('dlt-end-date');
    if ($ed) {
      $end_date = new DateTime($end);
    } else {
      \DLT\Notices::addError(__('Invalid end date.', 'digilan-token'));
      wp_redirect(self::getAdminUrl('connections'));
      exit();
    }
```

2023-01-12 14:00 UTC, dohnuts commented on admin/digilan-admin.php
> +    if ($sd > $ed) {
^regle de codage ( petit if en premier, variable nommé en fonction du scope ..

2023-01-13 15:44 UTC, GroupeCitypassengerInc approved these changes

2023-01-13 15:58 UTC, merged